version: '3'
services:

  specify7:
    image: specifyconsortium/specify7-service:docker
    volumes:
      - "specify6:/opt/Specify:ro"
      - "static-files:/volumes/static-files"
    environment:
      - DATABASE_HOST=your-mysql-or-mariadb-host
      - DATABASE_PORT=3306
      - DATABASE_NAME=your-specify-database
      - MASTER_NAME=a-mysql-specify-master-user
      - MASTER_PASSWORD=the-corresponding-password
      - SECRET_KEY="change this to some unique random string"
      - WEB_ATTACHMENT_URL=http://your-asset-server/web-asset-store.xml
      - WEB_ATTACHMENT_KEY="your asset server access key"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - LOG_LEVEL=WARNING
      - SP7_DEBUG=false

  specify6:
    image: specifyconsortium/specify6-service:6.8.00
    volumes:
      - "specify6:/volumes/Specify"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "static-files:/volumes/static-files:ro"
      - "specify6:/volumes/specify6:ro"

      - "./nginx/specify.conf:/etc/nginx/conf.d/default.conf:ro"

  report-runner:
    image: specifyconsortium/report-runner
      
volumes:
  specify6:
  static-files:
