version: '3.7'
services:

  specify7-db1:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6:/opt/Specify:ro"
      - "static-files-db1:/volumes/static-files"
    environment:
      - DATABASE_HOST=your-mysql-or-mariadb-host
      - DATABASE_PORT=3306
      - DATABASE_NAME=first-specify-database
      - MASTER_NAME=a-mysql-specify-master-user
      - MASTER_PASSWORD=the-corresponding-password
      - SECRET_KEY=change this to some unique random string
      - ASSET_SERVER_URL=http://your-asset-server/web-asset-store.xml
      - ASSET_SERVER_KEY=your asset server access key
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - LOG_LEVEL=WARNING
      - SP7_DEBUG=false

  specify7-db2:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6:/opt/Specify:ro"
      - "static-files-db2:/volumes/static-files"
    environment:
      - DATABASE_HOST=your-mysql-or-mariadb-host
      - DATABASE_PORT=3306
      - DATABASE_NAME=second-specify-database
      - MASTER_NAME=a-mysql-specify-master-user
      - MASTER_PASSWORD=the-corresponding-password
      - SECRET_KEY=change this to some unique random string
      - ASSET_SERVER_URL=http://your-asset-server/web-asset-store.xml
      - ASSET_SERVER_KEY=your asset server access key
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - LOG_LEVEL=WARNING
      - SP7_DEBUG=false
      
  specify6:
    image: specifyconsortium/specify6-service:6.8.00
    volumes:
      - "specify6:/volumes/Specify"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "static-files-db1:/volumes/static-files-db1:ro"
      - "static-files-db2:/volumes/static-files-db2:ro"
      - "specify6:/volumes/specify6:ro"

      - "./nginx/specify.conf:/etc/nginx/conf.d/default.conf:ro"

  report-runner:
    image: specifyconsortium/report-runner
      
volumes:
  specify6:
  static-files-db1:
  static-files-db2:
