version: '3.7'
services:
  
  db1:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6.8.00:/opt/Specify:ro"
      - "db1-static-files:/volumes/static-files"
    environment:
      - DATABASE_NAME=sp7demofish
      - DATABASE_HOST=mariadb
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY="change this to some unique random string"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - SP7_DEBUG=true
      - LOG_LEVEL=DEBUG
  db2:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6.8.00:/opt/Specify:ro"
      - "db2-static-files:/volumes/static-files"
    environment:
      - DATABASE_NAME=sp7demofish
      - DATABASE_HOST=mariadb
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY="change this to some unique random string"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - SP7_DEBUG=true
      - LOG_LEVEL=DEBUG
  db3:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6.8.00:/opt/Specify:ro"
      - "db3-static-files:/volumes/static-files"
    environment:
      - DATABASE_NAME=sp7demofish
      - DATABASE_HOST=mariadb
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY="change this to some unique random string"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - SP7_DEBUG=true
      - LOG_LEVEL=DEBUG
  db4:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6.8.00:/opt/Specify:ro"
      - "db4-static-files:/volumes/static-files"
    environment:
      - DATABASE_NAME=sp7demofish
      - DATABASE_HOST=mariadb
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY="change this to some unique random string"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - SP7_DEBUG=true
      - LOG_LEVEL=DEBUG
  db5:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6.8.00:/opt/Specify:ro"
      - "db5-static-files:/volumes/static-files"
    environment:
      - DATABASE_NAME=sp7demofish
      - DATABASE_HOST=mariadb
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY="change this to some unique random string"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - SP7_DEBUG=true
      - LOG_LEVEL=DEBUG
  db6:
    image: specifyconsortium/specify7-service:docker
    init: true
    volumes:
      - "specify6.7.04:/opt/Specify:ro"
      - "db6-static-files:/volumes/static-files"
    environment:
      - DATABASE_NAME=test
      - DATABASE_HOST=mariadb
      - MASTER_NAME=master
      - MASTER_PASSWORD=master
      - SECRET_KEY="change this to some unique random string"
      - REPORT_RUNNER_HOST=report-runner
      - REPORT_RUNNER_PORT=8080
      - SP7_DEBUG=true
      - LOG_LEVEL=DEBUG

  specify6.7.04:
    image: specifyconsortium/specify6-service:6.7.04
    volumes:
      - "specify6.7.04:/volumes/Specify"
  specify6.8.00:
    image: specifyconsortium/specify6-service:6.8.00
    volumes:
      - "specify6.8.00:/volumes/Specify"

  nginx:
    environment:
      - FORCE_RECREATE=0e32a1b7-9fdc-4769-91c0-0b21788d39d4
    volumes:
      - "db1-static-files:/volumes/db1-static-files:ro"
      - "db2-static-files:/volumes/db2-static-files:ro"
      - "db3-static-files:/volumes/db3-static-files:ro"
      - "db4-static-files:/volumes/db4-static-files:ro"
      - "db5-static-files:/volumes/db5-static-files:ro"
      - "db6-static-files:/volumes/db6-static-files:ro"
      - "specify6.7.04:/volumes/specify6.7.04:ro"
      - "specify6.8.00:/volumes/specify6.8.00:ro"

volumes:
  db1-static-files:
  db2-static-files:
  db3-static-files:
  db4-static-files:
  db5-static-files:
  db6-static-files:

  specify6.7.04:
  specify6.8.00:
